// === ENHANCED TIERS ===
export const TIERS = {
  freemium: {
    dailyLimit: 3,
    indicatorLimit: 7,
    ai: ["gpt4"],
    cooldown: 300,
    icon: "🆓",
  },
  premium: {
    dailyLimit: 10,
    indicatorLimit: 15,
    ai: ["gpt4", "gemini"],
    cooldown: 60,
    icon: "⭐",
  },
  pro: {
    dailyLimit: 30,
    indicatorLimit: Infinity,
    ai: ["gpt4", "deepseek", "gemini"],
    cooldown: 5,
    icon: "⚡",
    specialFeatures: ["unlimited"],
  },
};

export const INDICATOR_GROUPS = {
  freemium: [
    "Support & Resist",
    "Volume",
    "MACD",
    "Candlestick Pattern",
    "Stochastic",
    "Stop Level",
    "Relative Stock Index",
  ],
  premium: [
    "Support & Resist",
    "Volume",
    "MACD",
    "Candlestick Pattern",
    "Stochastic",
    "Stop Level",
    "Fair Value Gap",
    "Momentum",
    "Bollinger",
    "Relative Stock Index",
    "Order Block",
    "Trend",
    "System (Long/Short)",
    "ADX",
    "Parabolic SAR",
  ],
  pro: [
    "Relative Stock Index",
    "MACD",
    "Bollinger",
    "Volume",
    "Fibonacci",
    "Fair Value Gap",
    "Stochastic",
    "Candlestick Pattern",
    "Recent Price Action",
    "Support & Resist",
    "Trend",
    "Trend ROC",
    "CCI",
    "Momentum",
    "Baseline",
    "Volatility Filter",
    "Stop Level",
    "Order Block",
    "Liquidity Block",
    "System (Long/Short)",
    "Bull/Bear Cross",
    "ADX",
    "Explosion",
    "Parabolic SAR",
    "ATR",
    "Pivot Points",
    "Forex Swing Trader",
    "EMA",
    "SMA",
  ],
};

export const MARKET_SYMBOLS = {
  forex: ["XAU/USD", "EUR/USD", "GBP/USD", "USD/JPY", "AUD/USD"],
  crypto: ["BTC/USD", "ETH/USD", "BNB/USD", "SOL/USD", "DOGE/USD"],
};

export const TIMEFRAMES = [
  "1min",
  "5min",
  "15min",
  "30min",
  "1h",
  "2h",
  "4h",
  "1day",
  "1week",
  "1month",
];
